### ISSUE TITLE
使用kiwi-linter怎么一键抽取项目中所有的中文生成文件，抽取的都是已经定义好的变量

### ISSUE THREAD

**Issue by nimiumiu** [HoseaLE/kiwi-linter-x#2]
vscode-i18n-linter.i18nFilesPattern设置"default": "/src//.+(vue|js|html|ts*)"
kiwi --init kiwi --export导出的是已经定义的变量跟文案
未自定义中文变量情况下，需要一键抽取项目中所有的中文生成文件，提供给翻译人员，目前有这样的功能吗？未看到有快捷键、命令

**Comment by hoseale** [comment]
不能一键提所有文件， 可以提取当前文件所有中文，命令是kiwigo

**Comment by nimiumiu** [comment]
指定目录下运行 npx kiwi go 没有效果，用法是否有误

**Comment by hoseale** [comment]
在vscode里，Ctrl+shfit+p 打开命令面板 ，在最顶部输入kiwi 应该有提示

**Comment by nimiumiu** [comment]
试了，提示“共找到xxx处可自动替换的文案，是否替换”点击：“Yes”后，没有任何变化

**Comment by hoseale** [comment]
点前面灯泡，一个一个提取试试

**Comment by nimiumiu** [comment]
项目大，人力成本高

**Comment by hoseale** [comment]
如个单个能提取，应该能整体也能提取;  这个无变化没复现

**Comment by hoseale** [comment]
这个插件有点bug，没替换为ts()形式，还是原本的I18n.xx，应该有变化才对

**Comment by hoseale** [comment]
这个可能是vue文件的原因，升级为最新kiwi–linter试试

**Comment by nimiumiu** [comment]
### 原项目更新了一版支持了百度翻译：
使用百度翻译 api 需要在工程的 config 配置中配置好 appId 和 appKey；
当用户使用 kiwi --extract 命令时，如果 config 中配置了百度翻译 API 的 AppId 和 Token，则使用百度翻译替换原来的 Google 翻译；若是同时配置了 googleApiKey 和 百度翻译的 appId、appKey，则优先使用 Google 翻译

### 我试了之后
```
"baiduTranslate": {
    "appId": "",
    "appKey": ""
 },
```
配置好了百度翻译的AppId和token， 执行kiwi --extract 命令时，一直提示：请配置googleApiKey

**Comment by hoseale** [comment]
这个是kiwi-cli的问题，我不清楚; 有可能是config文件名称或者路径不对，自己看下源码哇
